/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wangxiancan_rtsp_player_can_JniUtils */

#ifndef _Included_com_example_wangxiancan_rtsp_player_can_JniUtils
#define _Included_com_example_wangxiancan_rtsp_player_can_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wangxiancan_rtsp_player_can_JniUtils
 * Method:    GetH264Frame
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_wangxiancan_rtsp_1player_1can_JniUtils_GetH264Frame
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_wangxiancan_rtsp_player_can_JniUtils
 * Method:    OpenUrl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_wangxiancan_rtsp_1player_1can_JniUtils_OpenUrl
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
